services:
  moe-counter:
    container_name: moe-counter
    build: 
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    env_file: .env
    expose:
      - 3000
  moe-counter-mongo:
    image: mongo:8
    container_name: moe-counter-mongo
    volumes: 
      - ./count.db:/data/db
    expose:
      - 27017